/**
 * PDF 콘텐츠 템플릿
 * 교육 콘텐츠를 PDF로 렌더링하는 React-PDF 컴포넌트
 */

import { Document, Page, View, Text } from '@react-pdf/renderer';
import { pdfStyles, difficultyColors, difficultyLabels } from '../styles';
import type { GeneratedContent } from '@/lib/ai/schemas';

export interface ContentTemplateProps {
  content: GeneratedContent;
  metadata: {
    language: string;
    difficulty: string;
    targetAudience: string;
    createdAt: string;
  };
}

// 라벨 변환 헬퍼
const languageLabels: Record<string, string> = {
  python: 'Python',
  javascript: 'JavaScript',
  sql: 'SQL',
  java: 'Java',
  typescript: 'TypeScript',
  go: 'Go',
};

const difficultyLevelLabels: Record<string, string> = {
  beginner: '입문',
  intermediate: '중급',
  advanced: '고급',
};

const targetAudienceLabels: Record<string, string> = {
  non_tech_worker: '비전공 직장인',
  junior_developer: '주니어 개발자',
  manager: '관리자/임원',
  career_changer: '커리어 전환자',
};

function formatDate(dateString: string): string {
  return new Date(dateString).toLocaleDateString('ko-KR', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });
}

export function ContentTemplate({ content, metadata }: ContentTemplateProps) {
  const languageLabel = languageLabels[metadata.language] || metadata.language;
  const difficultyLabel = difficultyLevelLabels[metadata.difficulty] || metadata.difficulty;
  const audienceLabel = targetAudienceLabels[metadata.targetAudience] || metadata.targetAudience;

  return (
    <Document>
      <Page size="A4" style={pdfStyles.page}>
        {/* 헤더 */}
        <View style={pdfStyles.header}>
          <Text style={pdfStyles.headerLogo}>CodeGen AI</Text>
          <View style={pdfStyles.headerMeta}>
            <Text style={pdfStyles.headerMetaItem}>AI 기반 코딩 교육 콘텐츠</Text>
            <Text style={pdfStyles.headerMetaItem}>{formatDate(metadata.createdAt)}</Text>
          </View>
        </View>

        {/* 제목 */}
        <Text style={pdfStyles.title}>{content.title}</Text>

        {/* 메타 정보 뱃지 */}
        <View style={pdfStyles.badgeContainer}>
          <Text style={pdfStyles.badge}>{languageLabel}</Text>
          <Text style={pdfStyles.badge}>{difficultyLabel}</Text>
          <Text style={pdfStyles.badge}>{audienceLabel}</Text>
          <Text style={pdfStyles.badge}>
            읽기 시간: {content.estimatedReadTime}분
          </Text>
        </View>

        {/* 학습 목표 */}
        <View style={pdfStyles.section}>
          <Text style={pdfStyles.sectionTitle}>학습 목표</Text>
          <View style={pdfStyles.list}>
            {content.learningObjectives.map((objective, index) => (
              <View key={index} style={pdfStyles.listItem}>
                <Text style={pdfStyles.listBullet}>•</Text>
                <Text style={pdfStyles.listContent}>{objective}</Text>
              </View>
            ))}
          </View>
        </View>

        {/* 핵심 개념 */}
        <View style={pdfStyles.section}>
          <Text style={pdfStyles.sectionTitle}>핵심 개념</Text>
          <Text style={pdfStyles.paragraph}>{content.explanation}</Text>
        </View>

        {/* 예제 코드 */}
        <View style={pdfStyles.section}>
          <Text style={pdfStyles.sectionTitle}>예제 코드</Text>
          <View style={pdfStyles.codeBlock}>
            <Text style={pdfStyles.codeLanguage}>{languageLabel}</Text>
            <Text style={pdfStyles.codeText}>
              {content.codeExample.replace(/```[\w]*\n?/g, '').trim()}
            </Text>
          </View>
        </View>

        {/* 연습 문제 */}
        <View style={pdfStyles.section}>
          <Text style={pdfStyles.sectionTitle}>연습 문제</Text>
          {content.exercises.map((exercise, index) => (
            <View key={index} style={pdfStyles.exerciseCard}>
              <Text style={pdfStyles.exerciseQuestion}>
                Q{index + 1}. {exercise.question}
              </Text>
              <Text
                style={[
                  pdfStyles.exerciseDifficulty,
                  { color: difficultyColors[exercise.difficulty] || '#64748b' },
                ]}
              >
                [{difficultyLabels[exercise.difficulty] || exercise.difficulty}]
              </Text>
              {exercise.hint && (
                <Text style={pdfStyles.exerciseHint}>힌트: {exercise.hint}</Text>
              )}
            </View>
          ))}
        </View>

        {/* 핵심 요약 */}
        <View style={pdfStyles.section}>
          <Text style={pdfStyles.sectionTitle}>핵심 요약</Text>
          <View style={pdfStyles.summaryBox}>
            <Text style={pdfStyles.summaryText}>{content.summary}</Text>
          </View>
        </View>

        {/* 푸터 */}
        <View style={pdfStyles.footer} fixed>
          <Text style={pdfStyles.footerText}>Generated by CodeGen AI</Text>
          <Text
            style={pdfStyles.pageNumber}
            render={({ pageNumber, totalPages }) => `${pageNumber} / ${totalPages}`}
          />
        </View>
      </Page>
    </Document>
  );
}
